apiVersion: v1
kind: Service
metadata:
  name: k3s-kafka-external
  namespace: k3s-kafka
  labels:
    app: kafka
    component: broker
    service-type: nodeport
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - name: external
      port: 9094
      targetPort: 9094
      nodePort: 30092
