apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kafka-local-storage
  labels:
    app: kafka
    component: storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
