apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kafka-local-storage
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  nodePath: /mnt/ssd/kafka
