apiVersion: v1
kind: Service
metadata:
  name: k3s-kafka-headless
  namespace: k3s-kafka
  labels:
    app: kafka
    component: broker
    service-type: headless
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - name: plaintext
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093
