apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-topics-script
  namespace: his-kafka
data:
  create-topics.sh: |
    #!/bin/bash
    
    # Wait for Kafka to be ready
    echo "Waiting for Kafka to be ready..."
    until kafka-broker-api-versions --bootstrap-server his-kafka-0.his-kafka-headless.his-kafka.svc.cluster.local:9092 > /dev/null 2>&1; do
      echo "Kafka not ready yet, waiting..."
      sleep 2
    done
    
    echo "Kafka is ready. Creating topics..."
    
    # Create hospital-department topic
    kafka-topics --bootstrap-server his-kafka-0.his-kafka-headless.his-kafka.svc.cluster.local:9092 \
      --create \
      --topic hospital-department \
      --partitions 3 \
      --replication-factor 1 \
      --config retention.ms=604800000 \
      --config compression.type=gzip \
      --if-not-exists
    
    # Create hospital-designation topic
    kafka-topics --bootstrap-server his-kafka-0.his-kafka-headless.his-kafka.svc.cluster.local:9092 \
      --create \
      --topic hospital-designation \
      --partitions 3 \
      --replication-factor 1 \
      --config retention.ms=604800000 \
      --config compression.type=gzip \
      --if-not-exists
    
    echo "Topics created successfully!"
    
    # List all topics
    echo "Current topics:"
    kafka-topics --bootstrap-server his-kafka-0.his-kafka-headless.his-kafka.svc.cluster.local:9092 --list
    
    # Describe the topics
    echo ""
    echo "Topic details:"
    kafka-topics --bootstrap-server his-kafka-0.his-kafka-headless.his-kafka.svc.cluster.local:9092 \
      --describe \
      --topic hospital-department
    
    kafka-topics --bootstrap-server his-kafka-0.his-kafka-headless.his-kafka.svc.cluster.local:9092 \
      --describe \
      --topic hospital-designation
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-create-topics
  namespace: his-kafka
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: kafka-topics
        image: confluentinc/cp-kafka:7.8.0
        command:
        - /bin/bash
        - /scripts/create-topics.sh
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: kafka-topics-script
          defaultMode: 0755
